/**
 * setup.mjs — connecting the trip planner, without a login wall.
 *
 * The crew stores every trip in a self-hosted trip planner the user owns. The
 * backend connects on its own whenever it can (a login on file, a planner
 * already running in Docker on this machine, a still-valid ticket). Only when
 * none of those exist does index.mjs show ConnectPage: one click to run a
 * planner in Docker (the app generates the admin login), or a pointer to the
 * Settings row where an existing planner's address and login live.
 *
 * ConnectForm and RunCard are also embedded in the Settings page.
 */

import { createElement as h, useState, useEffect } from 'react'
import { Icon, Pill } from './theme.mjs'
import { getSetup, postJSON } from './data.mjs'
import { t } from './i18n.mjs'

const DEFAULT_ADDRESS = 'http://127.0.0.1:3000'

function Field({ label, hint, type, value, onChange, placeholder, disabled, inputMode }) {
  return h('label', { className: 'td-field' },
    h('span', { className: 'lbl' }, label, hint ? h('span', { className: 'hint' }, hint) : null),
    h('input', {
      type: type || 'text', value, disabled, placeholder, inputMode,
      onChange: (e) => onChange(e.target.value),
    }))
}

/**
 * Address / email / password with "Test connection" and "Save" — the Settings
 * row for a planner the user runs elsewhere. `onSaved` fires after a successful
 * save so the caller can refresh status.
 */
export function ConnectForm({ initial, onSaved, saveLabel }) {
  const [address, setAddress] = useState((initial && initial.trek_url) || DEFAULT_ADDRESS)
  const [email, setEmail] = useState((initial && initial.email) || '')
  const [password, setPassword] = useState('')
  const [busy, setBusy] = useState('') // '' | 'test' | 'save'
  const [msg, setMsg] = useState(null) // { good: bool, text }

  async function submit(testOnly) {
    setBusy(testOnly ? 'test' : 'save')
    setMsg(null)
    const body = { trek_url: address.trim(), email: email.trim(), test_only: testOnly }
    if (password) body.password = password
    const { ok, data } = await postJSON('/setup', body)
    setBusy('')
    if (ok) {
      setMsg({ good: true, text: testOnly ? t('setup_reachable_ok') : t('setup_saved') })
      if (!testOnly && onSaved) onSaved()
      return
    }
    let text
    if (data && data.reachable === false) text = t('setup_unreachable', { url: address.trim() })
    else if (data && data.authenticated === false) text = t('setup_unauth')
    else text = (data && data.error) || t('unknown_error')
    setMsg({ good: false, text })
  }

  return h('div', { className: 'td-form' },
    h(Field, { label: t('setup_address'), type: 'text', value: address, onChange: setAddress, placeholder: DEFAULT_ADDRESS, disabled: !!busy }),
    h(Field, { label: t('setup_email'), type: 'email', value: email, onChange: setEmail, placeholder: 'admin@example.com', disabled: !!busy }),
    h(Field, { label: t('setup_password'), type: 'password', value: password, onChange: setPassword, disabled: !!busy }),
    h('div', { className: 'td-form-row' },
      h(Pill, { small: true, disabled: !!busy, onClick: () => submit(true) }, busy === 'test' ? t('setup_testing') : t('setup_test')),
      h(Pill, { small: true, dark: true, disabled: !!busy, onClick: () => submit(false) }, busy === 'save' ? t('setup_saving') : (saveLabel || t('setup_save')))),
    msg ? h('div', { className: ['td-form-msg', msg.good ? 'ok' : 'bad'].join(' ') }, msg.text) : null)
}

/**
 * "Run it for me": one click starts the Docker-managed planner. The admin login
 * is generated by the backend and kept in trek.env on this machine; a "custom"
 * toggle exposes email / password / port for the few who want their own.
 */
export function RunCard({ setup, onDone, small }) {
  const canDocker = !!(setup && setup.docker_available)
  const [custom, setCustom] = useState(false)
  const [email, setEmail] = useState((setup && setup.email) || '')
  const [password, setPassword] = useState('')
  const [port, setPort] = useState(String((setup && setup.port) || 3000))
  const [busy, setBusy] = useState(false)
  const [msg, setMsg] = useState(null)

  async function start() {
    setBusy(true)
    setMsg(null)
    const body = { port: Number(port) || 3000 }
    if (custom) { body.email = email.trim(); body.password = password }
    const { ok, data } = await postJSON('/service/create', body)
    setBusy(false)
    if (ok) {
      setMsg({ good: true, text: t('run_created', { email: (data && data.email) || '', path: (data && data.env_path) || 'trek.env' }) })
      if (onDone) onDone()
      return
    }
    setMsg({ good: false, text: t('setup_create_failed', { error: (data && data.error) || t('unknown_error') }) })
  }

  return h('div', { className: ['td-run', small ? 'small' : ''].join(' ') },
    canDocker ? null : h('div', { className: 'td-form-msg bad', style: { marginTop: 0 } }, t('setup_no_docker')),
    h('div', { className: 'td-form-row' },
      h(Pill, { dark: true, disabled: busy || !canDocker, onClick: start }, h(Icon, { name: 'play', size: 16 }), busy ? t('setup_starting') : t('connect_run')),
      h('button', { type: 'button', className: 'td-linkbtn', disabled: busy || !canDocker, onClick: () => setCustom((v) => !v), 'aria-expanded': custom }, t('run_custom'))),
    h('p', { className: 'td-run-note' }, t('connect_run_note')),
    custom ? h('div', { className: 'td-form', style: { marginTop: 8 } },
      h(Field, { label: t('setup_email'), type: 'email', value: email, onChange: setEmail, placeholder: 'admin@example.com', disabled: busy }),
      h(Field, { label: t('setup_password'), hint: t('setup_password_hint'), type: 'password', value: password, onChange: setPassword, disabled: busy }),
      h(Field, { label: t('setup_port'), type: 'text', inputMode: 'numeric', value: port, onChange: setPort, disabled: busy })) : null,
    msg ? h('div', { className: ['td-form-msg', msg.good ? 'ok' : 'bad'].join(' ') }, msg.text) : null)
}

/** Shown instead of the trip page only while nothing connects on its own. Nothing is gated: Settings is one tap away. */
export function ConnectPage({ status, onOpenSettings, onDone }) {
  const [setup, setSetup] = useState(null)
  useEffect(() => {
    let on = true
    getSetup().then((s) => { if (on) setSetup(s) }).catch(() => { if (on) setSetup({}) })
    return () => { on = false }
  }, [])
  const trek = (status && status.trek) || {}
  const reachable = !!trek.reachable

  return h('div', { className: 'td-scroll' },
    h('div', { className: 'td-settings-bar' },
      h('div', { className: 'td-brand' }, h(Icon, { name: 'pin', size: 22, stroke: 2.2 }), t('brand')),
      h(Pill, { small: true, onClick: onOpenSettings }, h(Icon, { name: 'gear', size: 15 }), t('settings'))),
    h('div', { className: 'td-setup' },
      h('div', { className: 'td-setup-hero' },
        h('h1', null, reachable ? t('connect_h1_login') : t('connect_h1')),
        h('p', null, reachable ? t('connect_lead_login', { url: trek.url || '' }) : t('connect_lead'))),
      h('div', { className: 'td-setup-card' },
        reachable ? null : h(RunCard, { setup, onDone }),
        h('div', { className: 'td-form-row', style: { marginTop: reachable ? 0 : 18 } },
          h(Pill, { dark: reachable, onClick: onOpenSettings }, h(Icon, { name: 'gear', size: 16 }), reachable ? t('connect_enter_login') : t('connect_settings'))),
        h('p', { className: 'td-run-note' }, reachable ? t('connect_login_note') : t('connect_settings_note')))))
}
